-- -----------------------------------------------------
-- MySQL Script generated by MySQL Workbench
-- Thu Nov 21 14:48:57 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 2studimmo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `2studimmo` DEFAULT CHARACTER SET utf8 ;
USE `2studimmo` ;

-- -----------------------------------------------------
-- Table `2studimmo`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2studimmo`.`utilisateur` (
  `id_Utilisateur` INT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `mot_de_passe` VARCHAR(45) NOT NULL,
  `telephone` INT NOT NULL,
  `photo` VARCHAR(45) NULL,
  `type` ENUM('Locataire', 'Propriétaire', 'Admin') NOT NULL,
  PRIMARY KEY (`id_Utilisateur`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `2studimmo`.`favoris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2studimmo`.`favoris` (
  `id_favoris` INT NULL AUTO_INCREMENT,
  `date_ajout` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `utilisateur_id` INT NOT NULL,
  `annnce_id` INT NULL,
  PRIMARY KEY (`id_favoris`),
  INDEX `fk_favoris_Utilisateur_idx` (`utilisateur_id` ASC),
  CONSTRAINT `fk_favoris_Utilisateur`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `2studimmo`.`utilisateur` (`id_Utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `2studimmo`.`alerte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2studimmo`.`alerte` (
  `id_alerte` INT NULL AUTO_INCREMENT,
  `prix` DECIMAL(10,2) UNSIGNED NULL,
  `localisation` VARCHAR(255) NULL,
  `nombre_pieces` INT UNSIGNED NULL,
  `type` ENUM('Location', 'Vente', 'Colocation') NULL,
  `surface` FLOAT UNSIGNED NULL,
  `utilisateur_id` INT NOT NULL,
  PRIMARY KEY (`id_alerte`),
  INDEX `fk_alerte_Utilisateur_locataire_idx` (`utilisateur_id` ASC),
  CONSTRAINT `fk_alerte_Utilisateur_locataire`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `2studimmo`.`utilisateur` (`id_Utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `2studimmo`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2studimmo`.`notification` (
  `id_notification` INT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `date_envoie` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `utilisateur_id` INT NOT NULL,
  `alerte_id` INT NOT NULL,
  PRIMARY KEY (`id_notification`),
  INDEX `fk_notification_Utilisateur_idx` (`utilisateur_id` ASC),
  INDEX `fk_notification_alerte_idx` (`alerte_id` ASC),
  CONSTRAINT `fk_notification_Utilisateur`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `2studimmo`.`utilisateur` (`id_Utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notification_alerte`
    FOREIGN KEY (`alerte_id`)
    REFERENCES `2studimmo`.`alerte` (`id_alerte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `2studimmo`.`annonce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2studimmo`.`annonce` (
  `id_annonce` INT NULL,
  `titre` VARCHAR(150) NOT NULL,
  `prix` DECIMAL(10,2) UNSIGNED NOT NULL,
  `description` TEXT NOT NULL,
  `localisation` VARCHAR(255) NOT NULL,
  `date_publication` DATETIME NOT NULL DEFAULT current_timestamp(),
  `statut` ENUM('Actif', 'Inactif', 'Supprimé') NOT NULL,
  `surface` FLOAT UNSIGNED NOT NULL,
  `type` ENUM('Location', 'Vente', 'Colocation') NOT NULL,
  `nombre_colocataires_max` INT UNSIGNED NULL,
  `nombre_pieces` INT UNSIGNED NOT NULL,
  `utilisateur_id` INT NOT NULL,
  `favoris_id_favoris` INT NOT NULL,
  `notification_id_notification` INT NOT NULL,
  PRIMARY KEY (`id_annonce`, `utilisateur_id`, `favoris_id_favoris`),
  INDEX `fk_annonce_Utilisateur_idx` (`utilisateur_id` ASC),
  INDEX `fk_annonce_favoris1_idx` (`favoris_id_favoris` ASC),
  INDEX `fk_annonce_notification1_idx` (`notification_id_notification` ASC),
  CONSTRAINT `fk_annonce_Utilisateur`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `2studimmo`.`utilisateur` (`id_Utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_annonce_favoris1`
    FOREIGN KEY (`favoris_id_favoris`)
    REFERENCES `2studimmo`.`favoris` (`id_favoris`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_annonce_notification1`
    FOREIGN KEY (`notification_id_notification`)
    REFERENCES `2studimmo`.`notification` (`id_notification`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2studimmo`.`galerie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2studimmo`.`galerie` (
  `id_galerie` INT NULL AUTO_INCREMENT,
  `date_depot` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `annonce_id` INT NOT NULL,
  PRIMARY KEY (`id_galerie`),
  INDEX `fk_galerie_annonce_idx` (`annonce_id` ASC),
  CONSTRAINT `fk_galerie_annonce`
    FOREIGN KEY (`annonce_id`)
    REFERENCES `2studimmo`.`annonce` (`id_annonce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2studimmo`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2studimmo`.`photo` (
  `id_photo` INT NULL AUTO_INCREMENT,
  `path` VARCHAR(255) NOT NULL,
  `galerie_id` INT NOT NULL,
  PRIMARY KEY (`id_photo`),
  INDEX `fk_photo_galerie_idx` (`galerie_id` ASC),
  CONSTRAINT `fk_photo_galerie`
    FOREIGN KEY (`galerie_id`)
    REFERENCES `2studimmo`.`galerie` (`id_galerie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2studimmo`.`dossier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2studimmo`.`dossier` (
  `id_dossier` INT NULL AUTO_INCREMENT,
  `statut` ENUM('complet', 'incomplet') NOT NULL,
  `utilisateur_id_Utilisateur` INT NOT NULL,
  PRIMARY KEY (`id_dossier`),
  INDEX `fk_dossier_utilisateur1_idx` (`utilisateur_id_Utilisateur` ASC),
  CONSTRAINT `fk_dossier_utilisateur1`
    FOREIGN KEY (`utilisateur_id_Utilisateur`)
    REFERENCES `2studimmo`.`utilisateur` (`id_Utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2studimmo`.`candidature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2studimmo`.`candidature` (
  `id_candidature` INT NULL AUTO_INCREMENT,
  `date_depot` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `statut` ENUM('En attente', 'Accepté', 'Rejeté') NOT NULL DEFAULT 'En attente',
  `utilisateur_id` INT NOT NULL,
  `annonce_id` INT NOT NULL,
  `utilisateur_id_Utilisateur` INT NOT NULL,
  `dossier_id_dossier` INT NOT NULL,
  PRIMARY KEY (`id_candidature`, `utilisateur_id_Utilisateur`),
  INDEX `fk_candidature_Utilisateur_idx` (`utilisateur_id` ASC),
  INDEX `fk_candidature_annonce_idx` (`annonce_id` ASC),
  INDEX `fk_candidature_utilisateur1_idx` (`utilisateur_id_Utilisateur` ASC),
  INDEX `fk_candidature_dossier1_idx` (`dossier_id_dossier` ASC),
  CONSTRAINT `fk_candidature_Utilisateur`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `2studimmo`.`utilisateur` (`id_Utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidature_annonce`
    FOREIGN KEY (`annonce_id`)
    REFERENCES `2studimmo`.`annonce` (`id_annonce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidature_utilisateur1`
    FOREIGN KEY (`utilisateur_id_Utilisateur`)
    REFERENCES `2studimmo`.`utilisateur` (`id_Utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidature_dossier1`
    FOREIGN KEY (`dossier_id_dossier`)
    REFERENCES `2studimmo`.`dossier` (`id_dossier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2studimmo`.`avis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2studimmo`.`avis` (
  `id_avis` INT NULL AUTO_INCREMENT,
  `note` INT UNSIGNED NULL DEFAULT 0,
  `contenue` TEXT NULL,
  `utilisateur_id` INT NOT NULL,
  `annonce_id` INT NOT NULL,
  PRIMARY KEY (`id_avis`, `annonce_id`),
  INDEX `fk_avis_annonce_idx` (`annonce_id` ASC),
  INDEX `fk_avis_Utilisateur_idx` (`utilisateur_id` ASC),
  CONSTRAINT `fk_avis_Utilisateur`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `2studimmo`.`utilisateur` (`id_Utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avis_annonce`
    FOREIGN KEY (`annonce_id`)
    REFERENCES `2studimmo`.`annonce` (`id_annonce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2studimmo`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2studimmo`.`message` (
  `id_message` INT NULL AUTO_INCREMENT,
  `contenue` TEXT NOT NULL,
  `date_envoi` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `utilisateur_id` INT NOT NULL,
  `annonce_id` INT NOT NULL,
  PRIMARY KEY (`id_message`),
  INDEX `fk_massage_Utilisateur_idx` (`utilisateur_id` ASC),
  INDEX `fk_message_annonce_idx` (`annonce_id` ASC),
  CONSTRAINT `fk_massage_Utilisateur`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `2studimmo`.`utilisateur` (`id_Utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_annonce`
    FOREIGN KEY (`annonce_id`)
    REFERENCES `2studimmo`.`annonce` (`id_annonce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2studimmo`.`suivie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2studimmo`.`suivie` (
  `id_suivie` INT NULL AUTO_INCREMENT,
  `etat` ENUM('En cours', 'Terminé', 'Annulé') NOT NULL DEFAULT 'En cours',
  `utilisateur_id` INT NOT NULL,
  `candidature_id` INT NOT NULL,
  PRIMARY KEY (`id_suivie`),
  INDEX `fk_suivie_Utilisateur_idx` (`utilisateur_id` ASC),
  INDEX `fk_favoris_candidature_idx` (`candidature_id` ASC),
  CONSTRAINT `fk_suivie_Utilisateur`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `2studimmo`.`utilisateur` (`id_Utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favoris_candidature`
    FOREIGN KEY (`candidature_id`)
    REFERENCES `2studimmo`.`candidature` (`id_candidature`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2studimmob`.`faq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2studimmo`.`faq` (
  `id_faq` INT NULL AUTO_INCREMENT,
  `question` TEXT NOT NULL,
  `reponse` TEXT NOT NULL,
  `admin_id` INT NOT NULL,
  PRIMARY KEY (`id_faq`),
  INDEX `fk_FAQ_Utilisateur_Admin_idx` (`admin_id` ASC),
  CONSTRAINT `fk_FAQ_Utilisateur_Admin`
    FOREIGN KEY (`admin_id`)
    REFERENCES `2studimmo`.`utilisateur` (`id_Utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2studimmo`.`cgu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2studimmo`.`cgu` (
  `id_cgu` INT NULL AUTO_INCREMENT,
  `contenu` TEXT NOT NULL,
  `admin_id` INT NOT NULL,
  PRIMARY KEY (`id_cgu`),
  INDEX `fk_cgu_Utilisateur_Admin_idx` (`admin_id` ASC),
  CONSTRAINT `fk_cgu_Utilisateur_Admin`
    FOREIGN KEY (`admin_id`)
    REFERENCES `2studimmo`.`utilisateur` (`id_Utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2studimmo`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2studimmo`.`document` (
  `id_document` INT NULL AUTO_INCREMENT,
  `nom_fichier` VARCHAR(255) NOT NULL,
  `chemin_fichier` VARCHAR(500) NOT NULL,
  `date_ajout` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `dossier_id` INT NOT NULL,
  PRIMARY KEY (`id_document`),
  INDEX `fk_document_dossier_idx` (`dossier_id` ASC),
  CONSTRAINT `fk_document_dossier`
    FOREIGN KEY (`dossier_id`)
    REFERENCES `2studimmo`.`dossier` (`id_dossier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
